#!/usr/bin/env python3
"""Generate the standalone distribution from the maintained public headers."""

import argparse
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent.parent
HEADERS = ("modint", "simd", "memory", "ntt", "poly", "fastpoly")
LITERAL_MARKER = "@FASTPOLY_LITERAL_"


def compact(source: str) -> str:
    """Strip comments and blank lines without changing C++ literals."""
    if LITERAL_MARKER in source:
        raise ValueError("literal marker collides with header contents")
    literals = []
    out = []
    i = 0
    while i < len(source):
        if source.startswith("//", i):
            end = source.find("\n", i)
            i = len(source) if end == -1 else end
        elif source.startswith("/*", i):
            end = source.find("*/", i + 2)
            if end == -1:
                raise ValueError("unterminated block comment")
            out.append(" " + "\n" * source[i:end + 2].count("\n"))
            i = end + 2
        elif source.startswith('R"', i):
            opening = source.find("(", i + 2)
            if opening == -1 or opening - (i + 2) > 16:
                raise ValueError("invalid raw string delimiter")
            delimiter = source[i + 2:opening]
            closing = ")" + delimiter + '"'
            end = source.find(closing, opening + 1)
            if end == -1:
                raise ValueError("unterminated raw string literal")
            end += len(closing)
            out.append(f"{LITERAL_MARKER}{len(literals)}@")
            literals.append(source[i:end])
            i = end
        elif source[i] in ('"', "'") and not (
            source[i] == "'" and i > 0 and i + 1 < len(source)
            and source[i - 1].isalnum() and source[i + 1].isalnum()
        ):
            quote = source[i]
            end = i + 1
            while end < len(source):
                if source[end] == "\\":
                    end += 2
                elif source[end] == quote:
                    end += 1
                    break
                else:
                    end += 1
            else:
                raise ValueError("unterminated quoted literal")
            out.append(f"{LITERAL_MARKER}{len(literals)}@")
            literals.append(source[i:end])
            i = end
        else:
            out.append(source[i])
            i += 1
    source = "".join(out)
    source = "\n".join(line.rstrip() for line in source.splitlines() if line.strip()) + "\n"
    pattern = re.compile(re.escape(LITERAL_MARKER) + r"(\d+)@")
    return pattern.sub(lambda match: literals[int(match[1])], source)


def header_body(name: str) -> str:
    path = ROOT / "include" / "fastpoly" / f"{name}.hpp"
    source = path.read_text(encoding="utf-8")
    guard = f"FASTPOLY_{name.upper()}_HPP"
    lines = source.splitlines(keepends=True)
    opening = next((i for i, line in enumerate(lines) if line.strip() == f"#ifndef {guard}"), None)
    if opening is None or lines[opening + 1].strip() != f"#define {guard}":
        raise ValueError(f"unexpected include guard in {path}")
    last = max(i for i, line in enumerate(lines) if line.strip())
    if not re.fullmatch(r"#endif(?:\s*//.*)?", lines[last].strip()):
        raise ValueError(f"unexpected closing guard in {path}")
    lines = lines[opening + 2:last]
    # Conditional system includes (SIMD intrinsics) retain their original order.
    lines = [line for line in lines if not re.fullmatch(
        r'\s*#\s*include\s+"fastpoly/[^"\n]+\.hpp"\s*\n?', line
    )]
    return compact("".join(lines))


def generate() -> str:
    banner = (
        "// fastpoly - standalone C++20 header.\n"
        "// Generated by scripts/amalgamate.py; edit include/fastpoly/*.hpp.\n"
        "#ifndef FASTPOLY_SINGLE_HPP\n"
        "#define FASTPOLY_SINGLE_HPP\n"
    )
    return banner + "".join(header_body(name) for name in HEADERS) + "#endif\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=ROOT / "fastpoly.hpp")
    parser.add_argument("--check", action="store_true", help="fail if the output needs regeneration")
    args = parser.parse_args()
    generated = generate()
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            print(f"{args.output} is stale; run scripts/amalgamate.py", file=sys.stderr)
            return 1
    else:
        args.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
